### ISSUE TITLE
Tab Glutton requiring access to all data on all websites visited

### ISSUE THREAD

**Issue by lodewykk** [nsand/tab-glutton#21]
Tab Glutton now requires the new permissions: "Read and change all your data on the websites that you visit".

Why is this? Is there a way to design Tab Glutton to get around requiring this permission?

**Comment by lodewykk** [comment]
I see the permissions didn't change, Chrome just started complaining about permissions since your last change in 2010.

**Comment by nsand** [comment]
Yup, this has been a requirement since the beginning. Going to resolve the issue.
