### ISSUE TITLE
Show if tab is pinned?

### ISSUE THREAD

**Issue by orschiro** [nsand/tab-glutton#36]
Dear @nsand,

What a great extension. Thank you! :-)

I am wondering if we can somehow display an icon or something when a tab is pinned. 

What do you think?

Yours,

Robert

**Comment by nsand** [comment]
Thanks! I'm glad that you're enjoying the extension.

I really like the idea, and it should be possible! I'll take a stab at it as soon as I can.

**Comment by orschiro** [comment]
Wow, thank you very much! :-)

Can you let me know once you want me to test it?

**Comment by nsand** [comment]
Hey @orschiro . I just uploaded the latest version of Tab Glutton to the Chrome store, which adds the ability to toggle pinned tabs in addition to showing the pinned status. Hopefully it will be available to you shortly.

![image](https://cloud.githubusercontent.com/assets/181819/23348441/24c79f08-fc78-11e6-9c47-658a458a3adb.png)

Implemented by d78f7b2

**Comment by orschiro** [comment]
Oh, wow.

This looks great.

Thank you so much! :-)

**Comment by nsand** [comment]
You're welcome. Thank you for the feature request!
