### ISSUE TITLE
React Context Themes and playing media indication

### ISSUE THREAD

**Issue by shapkarin** [nsand/tab-glutton#38]
Hello. Thanks for a nice extension. 

I plan to add to it:
- [x] Themes with React Context (or with Styled-Components ThemeProvider)
- [x] Dark theme
- [x] Show (in list) what tab is playing media now

It's been a while since last comments and updates so I need to know are you able to review some changes.

Next it's I'll try to help with other enhancement from this repo. For example I like keyboard navigation and add other tab actions.

Also it's nice to save search and list state even if user close popup.

**Comment by nsand** [comment]
Hi @shapkarin thanks for your interest and the kind words! I'd love to accept contributions to the project, and I'll certainly be available to review the changes. These all sound like great additions to me. Thanks so much for offering to help.

**Comment by shapkarin** [comment]
Cool then :-) I did `playing media indication`. It's too raw now and I think about design)
Hope that at this week I will provide a PR with all my proposals.

**Comment by shapkarin** [comment]
heh, I didn't expect that Github will track all squashes and fixups.. but I glad to say the soon I will prepare some new user settings for themes.

**Comment by shapkarin** [comment]
Almost done with my proposals. Just need to migrate tab-item, change separator color and fix current tab indication.
<img width="399" alt="Снимок экрана 2020-01-30 в 19 10 29" src="https://user-images.githubusercontent.com/1463086/73467476-6e1f7e80-4394-11ea-95c5-39ee3345a7b3.png">

You can find themes config at https://github.com/shapkarin/tab-glutton/blob/styled-components/src/themes.js

Also I have some design problems to solve.

Hope soon I will prepare the PR.

**Comment by shapkarin** [comment]
@nsand I have some troubles with https://github.com/shapkarin/tab-glutton/blob/styled-components/src/options/components/options.jsx
It's about `dense`. Maybe I will find time to solve it soon. But maybe you can have a look? I didn't fully migrate that option yet.

**Comment by shapkarin** [comment]
Closed with #40
